'use client'
import { useState } from 'react'
import Link from 'next/link'
import { ExternalLink, FileText, FolderKanban, Gauge, Settings } from 'lucide-react'

export default function AdminPage(){
 const [auth,setAuth]=useState(false); const [password,setPassword]=useState('')
 if(!auth) return <main className="admin-login"><div className="admin-login-card"><span className="admin-logo">MBZ</span><p>CONTENT STUDIO</p><h1>پنل مدیریت وبسایت شخصی</h1><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="رمز ورود"/><button onClick={()=>password===(process.env.NEXT_PUBLIC_ADMIN_PASSWORD||'mbz-admin')?setAuth(true):alert('رمز اشتباه است')}>ورود به پنل</button><small>رمز پیش‌فرض: mbz-admin</small></div></main>
 return <main className="admin-shell"><aside><div className="admin-brand"><span>MBZ</span><div><b>Content Studio</b><small>Personal website</small></div></div><nav><button className="active"><Gauge/>Overview</button><button><FolderKanban/>Projects</button><button><FileText/>Writing</button><button><Settings/>Settings</button></nav><Link href="/fa" target="_blank">مشاهده سایت<ExternalLink size={16}/></Link></aside><section className="admin-main"><header><div><p>OVERVIEW</p><h1>وبسایت شخصی شما</h1></div><button>Publish changes</button></header><div className="admin-stats"><article><small>Projects</small><strong>03</strong><span>Case studies</span></article><article><small>Writing</small><strong>03</strong><span>Draft ideas</span></article><article><small>Languages</small><strong>02</strong><span>FA / EN</span></article></div><div className="admin-grid"><section><h2>Content structure</h2><div className="admin-list"><div><span>01</span><b>Hero & positioning</b><small>components/home.tsx</small></div><div><span>02</span><b>Projects & metrics</b><small>data/site.ts</small></div><div><span>03</span><b>Experience & skills</b><small>data/site.ts</small></div><div><span>04</span><b>Writing</b><small>app/[locale]/writing</small></div></div></section><section className="admin-note"><p>STATIC-FIRST CMS</p><h2>سریع، امن و بدون دیتابیس اجباری</h2><p>این نسخه برای انتشار مطمئن روی Vercel طراحی شده است. اطلاعات اصلی در فایل data/site.ts نگهداری می‌شوند. در مرحله بعد می‌توان Sanity یا Supabase را بدون تغییر UI به این پنل متصل کرد.</p></section></div></section></main>
}