'use client'

import Image from 'next/image'
import Link from 'next/link'
import { motion } from 'framer-motion'
import { ArrowDownRight, ArrowUpRight, Mail, MapPin } from 'lucide-react'
import { experience, projects, skills, type Locale } from '@/data/site'
import { SiteShell } from './site-shell'

const text = {
  fa: { eyebrow:'PRODUCT · OPERATIONS · SYSTEMS', titleA:'محصولاتی می‌سازم که', titleB:'پیچیدگی عملیات را', titleC:'به رشد تبدیل می‌کنند.', lead:'مدیر محصول و عملیات با تمرکز بر TravelTech، CRM، Marketplace و سیستم‌های داخلی مقیاس‌پذیر.', seeWork:'مشاهده پروژه‌ها', about:'درباره من', impact:'اثر قابل اندازه‌گیری', impactLead:'برای من طراحی محصول از UI شروع نمی‌شود؛ از مسئله، داده و رفتار واقعی تیم شروع می‌شود.', work:'Selected work', workTitle:'پروژه‌هایی در نقطه اتصال محصول، داده و عملیات.', viewCase:'مشاهده کیس‌استادی', journey:'مسیر حرفه‌ای', journeyTitle:'از اجرای عملیات واقعی تا ساخت سیستم‌هایی که آن را بهتر می‌کنند.', capabilities:'توانمندی‌ها', thinking:'نوشته‌ها و ایده‌ها', thinkingTitle:'درباره Product Ops، CRM و TravelTech می‌نویسم.', contactTitle:'بیایید یک مسئله واقعی را حل کنیم.', contactLead:'برای همکاری در محصول، عملیات، CRM و سیستم‌های سازمانی آماده گفتگو هستم.', email:'ارسال ایمیل', location:'مشهد، ایران' },
  en: { eyebrow:'PRODUCT · OPERATIONS · SYSTEMS', titleA:'I build products that', titleB:'turn operational complexity', titleC:'into measurable growth.', lead:'Product and operations leader focused on TravelTech, CRM, marketplaces and scalable internal systems.', seeWork:'View selected work', about:'About me', impact:'Measurable impact', impactLead:'For me, product design does not begin with UI. It begins with the problem, the data and the real behavior of teams.', work:'Selected work', workTitle:'Projects at the intersection of product, data and operations.', viewCase:'View case study', journey:'Career journey', journeyTitle:'From running real operations to building systems that make them better.', capabilities:'Capabilities', thinking:'Writing & ideas', thinkingTitle:'Notes on Product Ops, CRM and TravelTech.', contactTitle:'Let’s solve something real.', contactLead:'Open to selected collaborations across product, operations, CRM and enterprise systems.', email:'Send an email', location:'Mashhad, Iran' }
}

const reveal = { initial:{opacity:0,y:24}, whileInView:{opacity:1,y:0}, viewport:{once:true,margin:'-80px'}, transition:{duration:.65} }

export function Home({ locale }: { locale: Locale }) {
 const t=text[locale]
 return <SiteShell locale={locale}><main>
  <section className="hero-section"><div className="hero-grid-bg"/><motion.div className="hero-copy" initial={{opacity:0,y:32}} animate={{opacity:1,y:0}} transition={{duration:.8}}><p className="eyebrow">{t.eyebrow}</p><h1><span>{t.titleA}</span><span className="gradient-text">{t.titleB}</span><span>{t.titleC}</span></h1><p className="hero-lead">{t.lead}</p><div className="hero-actions"><a href="#work" className="button button-dark">{t.seeWork}<ArrowDownRight size={18}/></a><a href="#story" className="button button-ghost">{t.about}</a></div></motion.div>
  <motion.div className="hero-visual" initial={{opacity:0,scale:.94}} animate={{opacity:1,scale:1}} transition={{duration:.9,delay:.12}}><div className="portrait-frame"><Image src="/profile.jpg" fill sizes="(max-width: 900px) 90vw, 38vw" alt="Mohammad Bagher Zolfaghari" priority/><div className="portrait-overlay"/><span className="floating-pill pill-one">TravelTech</span><span className="floating-pill pill-two">Product Ops</span><span className="floating-pill pill-three">CRM Systems</span></div><div className="availability"><span/><div><small>AVAILABLE FOR</small><b>SELECTED COLLABORATIONS</b></div></div></motion.div></section>
  <section className="impact-section"><motion.div className="section-heading split" {...reveal}><p className="section-kicker">01 / {t.impact}</p><h2>{t.impactLead}</h2></motion.div><div className="metric-grid">{[['3,500+','Hotels'],['40%','Less manual work'],['25%','SLA improvement'],['20–35%','Operational throughput']].map(([n,l],i)=><motion.div className={`metric-card metric-${i+1}`} key={n} {...reveal}><strong>{n}</strong><span>{l}</span></motion.div>)}</div></section>
  <section id="work" className="work-section"><motion.div className="section-heading" {...reveal}><p className="section-kicker">02 / {t.work}</p><h2>{t.workTitle}</h2></motion.div><div className="project-stack">{projects.map((p,i)=><motion.article className={`project-panel tone-${p.tone}`} key={p.slug} {...reveal}><div className="project-index">0{i+1}</div><div className="project-content"><div className="tag-row">{p.tags.map(tag=><span key={tag}>{tag}</span>)}</div><h3>{p.title[locale]}</h3><p>{p.summary[locale]}</p><Link href={`/${locale}/work/${p.slug}`} className="text-link">{t.viewCase}<ArrowUpRight size={18}/></Link></div><div className="project-metric"><strong>{p.metric}</strong><span>{p.metricLabel[locale]}</span></div></motion.article>)}</div></section>
  <section id="story" className="journey-section"><motion.div className="section-heading split" {...reveal}><p className="section-kicker">03 / {t.journey}</p><h2>{t.journeyTitle}</h2></motion.div><div className="timeline">{experience.map((item,i)=><motion.div className="timeline-row" key={item.org+item.period.en} {...reveal}><div className="timeline-number">{String(i+1).padStart(2,'0')}</div><div className="timeline-period">{item.period[locale]}</div><div><h3>{item.role[locale]}</h3><b>{item.org}</b><p>{item.detail[locale]}</p></div></motion.div>)}</div></section>
  <section className="capability-section"><motion.div className="section-heading" {...reveal}><p className="section-kicker">04 / {t.capabilities}</p><h2>Strategy × Systems × Execution</h2></motion.div><div className="skill-cloud">{skills.map(s=><motion.span key={s} {...reveal}>{s}</motion.span>)}</div></section>
  <section className="writing-teaser"><div><p className="section-kicker">05 / {t.thinking}</p><h2>{t.thinkingTitle}</h2></div><Link className="circle-link" href={`/${locale}/writing`}><ArrowUpRight size={34}/></Link></section>
  <section id="contact" className="contact-section"><div className="contact-glow"/><motion.div {...reveal}><p className="section-kicker">06 / Contact</p><h2>{t.contactTitle}</h2><p>{t.contactLead}</p><div className="contact-actions"><a className="button button-light" href="mailto:mbz1372@gmail.com"><Mail size={18}/>{t.email}</a><span><MapPin size={17}/>{t.location}</span></div></motion.div></section>
 </main></SiteShell>
}